# Generated by Django 5.0.1 on 2024-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('ticket_number', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('create_date', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('update_date', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('parent_ticket_id', models.TextField(blank=True, null=True)),
                ('assignee', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('due_date', models.TextField(blank=True, null=True)),
                ('rank', models.TextField(blank=True, null=True)),
                ('estimation', models.IntegerField(blank=True, null=True)),
                ('spent', models.IntegerField(blank=True, null=True)),
                ('workgroup', models.TextField(blank=True, null=True)),
                ('resolutio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('history_property_name', models.TextField(blank=True, null=True)),
                ('history_date', models.TextField(blank=True, null=True)),
                ('history_version', models.TextField(blank=True, null=True)),
                ('history_change_type', models.TextField(blank=True, null=True)),
                ('history_change', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.TextField(blank=True, null=True)),
                ('sprint_status', models.TextField(blank=True, null=True)),
                ('sprint_start_date', models.TextField(blank=True, null=True)),
                ('sprint_end_date', models.TextField(blank=True, null=True)),
                ('ticket_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sprint',
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
