# Generated by Django 5.0.1 on 2024-11-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_entities_history_sprints_delete_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entities',
            old_name='resolutio',
            new_name='resolution',
        ),
    ]
